# Generated by Django 2.2.7 on 2019-12-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brandi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='clothes',
            field=models.ManyToManyField(related_name='closets', to='brandi.Cloth'),
        ),
    ]
