# Generated by Django 2.2.7 on 2019-12-11 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brandi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codicup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('top_url', models.CharField(blank=True, max_length=300)),
                ('bot_url', models.CharField(blank=True, max_length=300)),
                ('out_url', models.CharField(blank=True, max_length=300)),
                ('one_url', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
